from typing import Any

from ibapi.contract import Contract
from ibapi.order import Order
from ibapi.wrapper import EWrapper

class EClient:
    wrapper: EWrapper
    def __init__(self, wrapper: EWrapper) -> None: ...
    def connect(self, host: str, port: int, clientId: int) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self) -> bool: ...
    def run(self) -> None: ...
    def reqCurrentTime(self) -> None: ...
    def reqMktData(
        self,
        reqId: int,
        contract: Contract,
        genericTickList: str,
        snapshot: bool,
        regulatorySnapshot: bool,
        mktDataOptions: list[Any],
    ) -> None: ...
    def reqHistoricalData(
        self,
        reqId: int,
        contract: Contract,
        endDateTime: str,
        durationStr: str,
        barSizeSetting: str,
        whatToShow: str,
        useRTH: int,
        formatDate: int,
        keepUpToDate: bool,
        chartOptions: list[Any],
    ) -> None: ...
    def reqRealTimeBars(
        self,
        reqId: int,
        contract: Contract,
        barSize: int,
        whatToShow: str,
        useRTH: bool,
        realTimeBarsOptions: list[Any],
    ) -> None: ...
    def cancelRealTimeBars(self, reqId: int) -> None: ...
    def reqPositions(self) -> None: ...
    def reqAccountSummary(self, reqId: int, groupName: str, tags: str) -> None: ...
    def cancelAccountSummary(self, reqId: int) -> None: ...
    def reqAllOpenOrders(self) -> None: ...
    def reqOpenOrders(self) -> None: ...
    def cancelOrder(self, orderId: int) -> None: ...
    def reqContractDetails(self, reqId: int, contract: Contract) -> None: ...
    def reqSecDefOptParams(
        self,
        reqId: int,
        underlyingSymbol: str,
        futFopExchange: str,
        underlyingSecType: str,
        underlyingConId: int | str,
    ) -> None: ...
    def reqAutoOpenOrders(self, bAutoBind: bool) -> None: ...
    def placeOrder(self, orderId: int, contract: Contract, order: Order) -> None: ...
