from .buy_and_hold import BuyAndHold
from .debt_trading import DebtTrading
from .diversification import Diversification
from .diversified_leverage import DiversifiedLeverage
from .fast_trading import FastTrading
from .intraday_momentum import IntradayMomentum
from .momentum import Momentum
from .simple import Simple
from .strangle import Strangle
