export type LeadRecord = {
  id: string;
  company_name: string;
  category: string;
  website: string | null;
  location: string | null;
  contact_name: string | null;
  contact_title: string | null;
  contact_email: string | null;
  linkedin_url: string | null;
  warm_intro_source: string | null;
  notes: string | null;
  estimated_budget: string | null;
  urgency: number;
  remote_friendly: boolean;
  ability_to_pay: number;
  fit_with_my_background: number;
  need_for_ai_product_help: number;
  relevance_to_lcs: number;
  relevance_to_decision_intelligence: number;
  family_office_or_wealth_fit: number;
  institutional_education_fit: number;
  accessibility_of_decision_maker: number;
  warm_intro_strength: number;
  remote_or_fractional_fit: number;
  fit_score: number;
  stage: string;
  next_action: string | null;
  last_contacted_date: string | null;
  follow_up_date: string | null;
  suggested_offer: string | null;
  personalized_angle: string | null;
  monthly_revenue_potential: string | null;
  objection_risk: string | null;
  confidence_level: string | null;
  priority_level: string;
  created_at: string;
  updated_at: string;
};
